sudo: required
services:
  - docker

script:
  - docker build -t krivi95/psz-real-estate-models src/streamlit\ app
  - docker images krivi95/psz-real-estate-models

before_deploy:
  - docker login -u krivi95 -p $DOCKER_PASSWORD

deploy:
  provider: script
  script: docker push krivi95/docker-travis-test
  on:
    branch: master

env:
  global:
    secure: EvxAe18vuh3AHk3ZuS/YavAgYkX1JYXQEHmscHiP8nZPI9GMIthmSzfsTA/M7is5vMXUFsfAZkokgULv/sr6iPtdRcbolVgQGukn0R9oYMTKQz9no20Q6md1dTgnFUJaKtP5LLS6hLeb327UuNsnl1Oe8Q72Zl0BPPS6IrD01ZmITCgJoBf5ETJM2hUebWBXfxWuhph5mzxpILT0bq52x0/gCe4oSev5asXl/q3SJteR4mOpzoqJZqYRA0S6mtiz6hS23SaIZ4GThhrMaoMu0cCk7tV5d1wF0KMbZh9ULWGG9YcTdg64cYMx0Bl5w0C2WGP41djpa9DHMk9NJ107PHz90jN03O15BSlPVwBA6IEMHZOcii92jpMkLRXwLap3a/32kB23cHCGbnPhXf4UUq9KqTPEJJQ2xtp6QTp6mlXpspFV8r2Py3BzkBWPgqYtI3O3N/LHxRQvRckeRadmKWyJ0PgjqKppVy20XYFjrVwTy8LwabieLrFQFBJlSG+u8XSIH/AmU1UngMClwcoqvFUNCcAwGtrAPtmKYLQ7Nkp1RK/PMEWqCIsRPoY6yUj+xO18iNMyfFKEHQJCAoAdJgsON+aV2PyZsu95VguPu88VWlvqpbRKPMwsc++ZNgEmlKgXdc/Ko7GrEiiyNYikXEltWCLaypaknels2p9EvfU=
