sudo: required
services:
  - docker

script:
  - docker build -t krivi95/psz-real-estate-models src/streamlit\ app
  - docker images krivi95/psz-real-estate-models

before_deploy:
  - docker login -u krivi95 -p $DOCKER_PASSWORD

deploy:
  provider: script
  script: docker push krivi95/psz-real-estate-models
  on:
    branch: master

env:
  global:
    secure: kpze9btenh2IuXjUp/LZJXYXy43H54PioFCup/FBgka2apglggDhBeOuw4Y5zOusjtv6n8tgPkG9KaqmUY6EnX2ecx+l5pAq8Uuyt/YFrRPHuh+kbUL5vyNDJLOHBLAlPG07HP8oEjqYgYU10pUZ5FHNwMvEKF7etJhO05HUTDvQzetvpVQjqHJsvY1SE31EVfdmMIR2+Q4H/4YBzunZxUjczJNDIsr7RPpOK9bcpH1NmOFZNL/20D0/iODAaGRngedBrlotm5sWkRtEhD7Vmq5W1QNRCPqV90M+YaVYlxdg4dKJNe2eKBT92LdPLX+GwQfqPWmoAi9xFHeX9PZ01BS7HWMiaz3+ycH6AKBDi1hZeUo4AavS9oRJktNKUES4JPeprl0d6tNI41Bx1Hj8ljUJJ6u90TZu/9+PGs6edyW4pXQ38k+UjjI2IHxHluqJolrKfe+b7FlBShlVqP7Hd1VXH3Q2A6ZAvk2Mtvc6aQhibGc6OEevJUYshm/oThF7eNPpoKtVAfmkWeuE4l/qCXnDGnNptHafTMRvjgwXSPh4nnCi9qIWHN9Mr0Gnh4IXxct+l1S2I7RcpUwC1haSvZZnZOBZYIFxdr7OKkvg5Ehp9jiQGlYWMVGpPDMdvVajPXOHr+vQ7+B3c8FCpkUisZOY4p8EX47OL55Y5ToqWNc=
